### ISSUE TITLE
Does not respond properly when first setting up on a Windows system

### ISSUE THREAD

**Issue by MBasial** [studioimaginaire/phue#10]
The procedure for Windows systems is not quite right, I think -- I won't pretend to know what I'm doing, but I can tell you what I did that made it work for me.

When I started a test program of mine ("CrimsonTide.py", does a "red alert on a submarine" effect), it failed in an unexpected way, reporting a type-conversion error (error message at bottom). I was expecting an error to the effect of "this program is not registered with the bridge" or some other authentication error.

I tracked it backwards to a failure during the **init** call on lines 360 and 361. 

```
    if os.access(os.getenv(USER_HOME),os.W_OK):
        self.config_file_path = os.path.join(os.getenv(USER_HOME),'.python_hue')
```

It seems that if USER_HOME is not defined as an environment variable, getenv() returns None, which is not being implicitly converted to a string. I added str() calls around os.getenv(), and that got it working. As I mentioned, I don't really know what I'm doing, so that may be a bad way to fix it.

Thank you for putting this together, I'm having fun playing with my lamps!

---

INFO:phue:Logging level set to info
INFO:phue:Attempting to connect to the bridge...
INFO:phue:Error opening config file, will attempt bridge registration
INFO:phue:Please press button on bridge to register application and call connect
() method
Traceback (most recent call last):
  File "CrimsonTide.py", line 59, in <module>
    main()
  File "CrimsonTide.py", line 20, in main
    lights = b.get_light_objects('name')
  File "C:\Users\Michael Basial\Documents\My Dropbox\Philips_Hue\phue-master\phu
e.py", line 483, in get_light_objects
    lights = self.request('GET', '/api/' + self.username + '/lights/')
TypeError: Can't convert 'NoneType' object to str implicitly

**Comment by Sandown** [comment]
Was this ever resolved? I'm having the issue running on Windows Server 2012 R2

I've replaced my username with "snipped" for security reasons:

 RESTART: C:\Users\"snipped"\AppData\Local\Programs\Python\Python35\hue-flux.py 
Discovering Hue bridges...
Traceback (most recent call last):
  File "C:\Users\"snipped"\AppData\Local\Programs\Python\Python35\phue.py", line 736, in connect
    with open(self.config_file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\"snipped"\\AppData\\Local\\Programs\\Python\\Python35\\.python_hue'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\"snipped"\AppData\Local\Programs\Python\Python35\hue-flux.py", line 251, in <module>
    bridge = phue.Bridge()
  File "C:\Users\"snipped"\AppData\Local\Programs\Python\Python35\phue.py", line 629, in __init__
    self.connect()
  File "C:\Users\"snipped"\AppData\Local\Programs\Python\Python35\phue.py", line 752, in connect
    self.register_app()
  File "C:\Users\"snipped"\AppData\Local\Programs\Python\Python35\phue.py", line 706, in register_app
    response = self.request('POST', '/api', registration_request)
  File "C:\Users\"snipped"\AppData\Local\Programs\Python\Python35\phue.py", line 647, in request
    connection = httplib.HTTPConnection(self.ip, timeout=10)
  File "C:\Users\"snipped"\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 762, in __init__
    (self.host, self.port) = self._get_hostport(host, port)
  File "C:\Users\"snipped"\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 794, in _get_hostport
    i = host.rfind(':')
AttributeError: 'NoneType' object has no attribute 'rfind'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\"snipped"\AppData\Local\Programs\Python\Python35\hue-flux.py", line 255, in <module>
    bridge = discover_and_connect_bridge()
  File "C:\Users\"snipped"\AppData\Local\Programs\Python\Python35\hue-flux.py", line 41, in discover_and_connect_bridge
    bridge = phue.Bridge(hub_ip)
UnboundLocalError: local variable 'hub_ip' referenced before assignment

**Comment by Sandown** [comment]
@natcl 

Forgot to mention, I'm running a small script on top of this called, hue-flux. See https://github.com/KpaBap/hue-flux

**Comment by natcl** [comment]
It doesn't seem to find the `.python_hue` config file, can you try locating it on your computer and telling the path ?

**Comment by Sandown** [comment]
.python_hue  does not exist, I think the script tries to create it to store some settings in. I've tried manually creating the file at the location where the script attempts to but I still get the same error

**Comment by natcl** [comment]
Seems like a problem with the script using phue that does'nt define hub_ip correctly...
You could always try calling phue from python manually to see if it behaves normally and creates the config file.


--
lecaude.com 
studioimaginaire.com

**Comment by Sandown** [comment]
Here's what I get if I try to run phue manually:

=============== RESTART: C:\Python36\Lib\site-packages\phue.py ===============
usage: phue.py [-h] --host HOST [--config-file-path CONFIG_FILE_PATH]
phue.py: error: the following arguments are required: --host

**Comment by natcl** [comment]
You need to specify a host which is the IP address of your bridge.

2017-02-21 11:02 GMT-05:00 Sandown <notifications@github.com>:

**Comment by Sandown** [comment]
I thought so but it doesn't seem to like me entering an IP after --host. Could you give me an example of the syntax / command I need to run? I appreciate the help, as you can guess I've no idea about Python. Small steps though :)

**Comment by Sandown** [comment]
Think I figured that bit out but now I get:

>>> phue.py --host ("IP removed for security") --config-file-path ("C:\\users\\snipped\\documents\\hue-flux-master")
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    phue.py --host ("IP removed for security") --config-file-path ("C:\\users\\snipped\\documents\\hue-flux-master")
NameError: name 'phue' is not defined

**Comment by natcl** [comment]
Try just this without specifying a config file.  The config file is
normally created automatically by phue the first time you connect:

python phue.py --host 192.168.1.1
Replace with your own IP

2017-02-21 11:18 GMT-05:00 Sandown <notifications@github.com>:

**Comment by Sandown** [comment]
Below is what I get from either CMD prompt or Python Shell:

C:\Users\snipped>python phue.py --host 192.168.20.14
python: can't open file 'phue.py': [Errno 2] No such file or directory

**Comment by Sandown** [comment]
Cheers I figured it out, you have to run phue.py first successfully with the commands you mentioned for it to create the settings file, hence why it was saying access denied (since the file didn't exist).

I've now got as fat as this:
C:\Python36>hue-flux.py
Discovering Hue bridges...
Found previously connected bridge
Traceback (most recent call last):
  File "C:\Python36\hue-flux.py", line 261, in <module>
    sunset_time = sun.get_sun(location)[1]  # Sunset time in 24hr format
  File "C:\Python36\sun.py", line 36, in get_sun
    data = json.loads(response)['moon_phase']
KeyError: 'moon_phase'

**Comment by Sandown** [comment]
Think I figured the above bit out, there's some settings I need to change in the hue-flux.py script at line 236:

location = "95050"  # Zip code or some other location string
bedtime = "21:00"
