### ISSUE TITLE
KeyError: 'lastupdated' with 'set_sensor_state' of an IP sensor

### ISSUE THREAD

**Issue by bennert** [studioimaginaire/phue#101]
Reproduction scenario:
bridgeDestination.set_sensor_state(5, 'presence', bridgeSource.get_sensor(6, 'state')['presence'])

Traceback:
  File "hueMotion.py", line 27, in <module>
    bridgeDestination.set_sensor_state(5, 'presence', bridgeSource.get_sensor(6, 'state')['presence'])
  File "build/bdist.linux-armv7l/egg/phue.py", line 991, in set_sensor_state
  File "build/bdist.linux-armv7l/egg/phue.py", line 1015, in set_sensor_content
KeyError: 'lastupdated'

Source code:
        del data["lastupdated"]

should be replace by:
        if "lastupdated" in data:
            del data["lastupdated"]

**Comment by natcl** [comment]
Can you send a pull-request ?

**Comment by bennert** [comment]
I'm new with committing to gitbub, but finally I created a pull-request: [https://github.com/studioimaginaire/phue/pull/102]

**Comment by bennert** [comment]
Verified pull request 102 => Result OK
