### ISSUE TITLE
Blink on Twitch event

### ISSUE THREAD

**Issue by Wikotikabesa** [studioimaginaire/phue#111]
I want my Philips Hue Lights blink when i get a follower/subscriber on Twitch.
[Physical_twitch_notifications](https://github.com/shughes-uk/physical_twitch_notifications) can do this, but I cant get it work. 
[I open an issue there and the Dev was verry helpful.](https://github.com/shughes-uk/physical_twitch_notifications/issues/1)
In the end, however, this was also at a loss. And send me here.
Can someone help here?
Thanks in advance.

**Comment by natcl** [comment]
The error means there is no lights called 'W_rgb2' on your Bridge.
Can you try naming the light you want to control  to 'W_rgb2' using your hue app on your phone ?

**Comment by Wikotikabesa** [comment]
There is a light called "W_rgb2".
U can see it at the end of the [second link ](https://github.com/shughes-uk/physical_twitch_notifications/issues/1)i've postet above.

**Comment by theunknownport** [comment]
Maybe you have to give id instead of the name
