### ISSUE TITLE
i can't turn on the light.....please help

### ISSUE THREAD

**Issue by thxkew** [studioimaginaire/phue#114]
>>> from phue import Bridge
>>> b = Bridge('192.168.1.100')
>>> b.set_light(1, 'on' , True)
No handlers could be found for logger "phue"
[[{u'error': {u'type': 3, u'description': u'resource, /lights/1/state, not available', u'address': u'/lights/1/state'}}]]

i code python in raspberry pi 3 but it alert error follow above. it seem can't connect the bridge or another problem i'm not sure. and  i have no i deal how to fix it. please help me to fix.

thank you so much

**Comment by Unintendedsideeffects** [comment]
You haven't run b.connect()
