### ISSUE TITLE
INFO - Is it possible to connect from internet?

### ISSUE THREAD

**Issue by RuBiCK** [studioimaginaire/phue#118]
I have an AWS lambda function that I want to trigger an hue ambience. I can open the communication from internet to my bride ( I really prefer don't do it) but I don't know how the bridge manage the auth devices.

AWS Lambda under the hood run in docker so there won't be any permanent ID of the device which is making the request to the bridge.

- Could you please explain a little bit about how authorisation works?
- Is it possible to make a request from internet?
- How can I get a permanent authorization with phue like a token?

Thanks!

**Comment by natcl** [comment]
phue is meant to communicate locally with your bridge, I wouldn't run it outside the network where the bridge is located...

**Comment by KaiTroendle** [comment]
But for example how does the ios-app connect to the bridge. I really want to be able to connect to the bridge outside of the network where the bridge is located

**Comment by andofrjando** [comment]
@KaiTroendle Have a look at my pull request #133 which facilitates this. It is still opened and not merged though, so you'd have to use my fork.
