### ISSUE TITLE
Can't connect to brige

### ISSUE THREAD

**Issue by fredrikj31** [studioimaginaire/phue#139]
Hey.

I can't connect to the brige...

I have tried the IPv4 the "192.168.*"
But without luck...

I just want to know how, and what ip address type I need to use to connect to my brige.

**Comment by SpootDev** [comment]
In my environment at home I run DHCP to hand  out addresses.  I just looked at the leases to find the IP.

**Comment by fredrikj31** [comment]
But what ip should i use for the connection to the Hub? @SpootDev

**Comment by SpootDev** [comment]
https://www.developers.meethue.com/documentation/getting-started 

Step 2 shows how to get IP to connect to.

**Comment by fredrikj31** [comment]
How do i check if its connected? @SpootDev

**Comment by fredrikj31** [comment]
Thanks for the answer @SpootDev. I tested it and it worked thanks alot :)
