### ISSUE TITLE
run_scene() gets unexpected keyword argument 'group'

### ISSUE THREAD

**Issue by AwesomeIndustry** [studioimaginaire/phue#145]
Hi, I've been trying to set a scene with `bridge.run_scene(room_name,scene_name)`, but I get this error:
```
Traceback (most recent call last):
  File "<pyshell#14>", line 1, in <module>
    bridge.run_scene("Entertainment Area 1","Savanna Sunset")
  File "/home/pi/.local/lib/python2.7/site-packages/phue.py", line 1166, in run_scene
    scenes = [x for x in self.scenes if x.name == scene_name]
  File "/home/pi/.local/lib/python2.7/site-packages/phue.py", line 1138, in scenes
    return [Scene(k, **v) for k, v in self.get_scene().items()]
TypeError: __init__() got an unexpected keyword argument 'group'
```
Am I doing something wrong?

(P.S: It appears that `bridge.scenes` no longer exists? Is there a better alternative than using `b.get_api()["scenes"]`?)

**Comment by Cazfri** [comment]
I think Philips must have updated their API and the scene code is written in such a way that it can't handle any more properties than exactly expected. I submitted https://github.com/studioimaginaire/phue/pull/143 with a fix, you can just copy or fork that for now if you like.

**Comment by natcl** [comment]
Pull request merged!
Thanks!


--
lecaude.com 
studioimaginaire.com

**Comment by richtems** [comment]
Can you please release a new version on PyPI? Would love that!
