### ISSUE TITLE
Global name 'PROTOCOL DNS' is not defined

### ISSUE THREAD

**Issue by requizm** [studioimaginaire/phue#146]
I had en error. I tried import ssl or _ssl but I still get the same error. Why?

**Comment by natcl** [comment]
I can't help you if you don't provide more information:
Platform, exact script, bridge version etc...

**Comment by requizm** [comment]
> I can't help you if you don't provide more information:
> Platform, exact script, bridge version etc...

You're right. Sorry for that issue with missing information. I don't remember anything anyway. So..
