### ISSUE TITLE
Please release new version to PyPI

### ISSUE THREAD

**Issue by Cazfri** [studioimaginaire/phue#147]
The most recent version of phue on PyPI is version 1.0, so the Scenes fix from #143 is not there. Pulling phue with `pip3 install phue` still results in the same error seen previous to #143. Please update the package on PyPI to reflect the most recent version of phue.

**Comment by natcl** [comment]
Will publish a new package after the holidays!


--
lecaude.com 
studioimaginaire.com

**Comment by PanderMusubi** [comment]
Thanks. Hope to see more pull requests merged, if possible.

**Comment by natcl** [comment]
I merged alot of pull requests recently, is there a specific one you're interested in?


--
lecaude.com 
studioimaginaire.com

**Comment by PanderMusubi** [comment]
Yes, please:
* https://github.com/studioimaginaire/phue/pull/98
* https://github.com/studioimaginaire/phue/pull/100
* https://github.com/studioimaginaire/phue/pull/133
* https://github.com/studioimaginaire/phue/pull/82
* https://github.com/studioimaginaire/phue/pull/24 (this might need further development, but some graceful degradation of several host names might improve finding bridge automatically, even though in some networks, hostname will not result in a succes at all.)

**Comment by natcl** [comment]
New release pushed !
