### ISSUE TITLE
Commit `e5e550bf` breaks UTF-8 encoding on Python 3

### ISSUE THREAD

**Issue by BlackLight** [studioimaginaire/phue#150]
Commit [e5e550bf](https://github.com/studioimaginaire/phue/commit/e5e550bf14bd3578db17de4046c8240fcfc1e446) seems to address UTF-8 encoding/decoding issues on Python 2 but it actually breaks it on Python 3.

Steps to replicate:

```python
# Python 3.5.3 (default, Sep 27 2018, 17:25:39)
>>> from phue import Bridge
>>> b = Bridge('hue')
>>> b.get_scene()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/blacklight/git_tree/phue/phue.py", line 1128, in get_scene
    return self.request('GET', '/api/' + self.username + '/scenes')
  File "/home/blacklight/git_tree/phue/phue.py", line 666, in request
    return json.loads(decodeString(response))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

`get_scene` works fine if I revert that commit.

[I have prepared a pull request](https://github.com/studioimaginaire/phue/pull/149) to address the issue - please consider merging ASAP as the encoding issue currently breaks any phue interaction on Python 3.

**Comment by natcl** [comment]
This worked in Python 3.6 for me, did you test it with a more recent version of Python ?


--
lecaude.com 
studioimaginaire.com

**Comment by natcl** [comment]
Fixed with latest commit.
