### ISSUE TITLE
Getting TypeError when calling anything past connect()

### ISSUE THREAD

**Issue by VariableIQC** [studioimaginaire/phue#179]
Whenever I try to use a function such as get_light() or get_api() after "successfully" connecting to the bridge, it errors out, saying 
`(Line 836 phue.py) TypeError: can only concatenate str (not "NoneType" to str).`

I went in and did a bit of debugging and found that the state variable looks like this:

`{'error': {'type': 1, 'address': '/lights', 'description': 'unauthorized user'}}`

App still works, and lights are on.

**Comment by natcl** [comment]
Can you check your home folder for a .python_hue file ? It should have your authorization info there.

**Comment by VariableIQC** [comment]
> Can you check your home folder for a .python_hue file ? It should have your authorization info there.

I looked in the directory where my program is and I don't see anything in there, same with the package installation directory.

**Comment by natcl** [comment]
Is his bridge authorized ? He needs to press the button too.

**Comment by VariableIQC** [comment]
Yes, it still throws the normal error when the bridge button isn't pressed. It's only after I sync with the bridge properly that I get that authorization issue

**Comment by natcl** [comment]
Can you check for the .python_hue file, it should be in the home/user folder.


--
lecaude.com 
studioimaginaire.com

**Comment by VariableIQC** [comment]
I'm using raspbian linux, where would it place the .python_hue file?

**Comment by natcl** [comment]
Most probably in /home/pi/.python_hue

**Comment by VariableIQC** [comment]
Doesn't appear to be there.

**Comment by natcl** [comment]
It’s a hidden file, make sure you do la -al in the terminal to see it.


--
lecaude.com 
studioimaginaire.com

**Comment by VariableIQC** [comment]
Alright, I do see the .python_hue file now.

**Comment by natcl** [comment]
Does it seem to contain your API key ?


--
lecaude.com 
studioimaginaire.com

**Comment by VariableIQC** [comment]
It contains the IP of the bridge and a username, yes. Could this cause issues when swapping between bridges or does it update itself?

**Comment by natcl** [comment]
If you redo the pairing it should work but you could always try deleting the file and re-pairing.

**Comment by VariableIQC** [comment]
Alright, if all else fails I'll delete the file and re-pair. I think it was just failing to overwrite the existing file (or just wasn't expecting it had to). Preciate the help
