### ISSUE TITLE
Offer a package for Ubuntu/Debian

### ISSUE THREAD

**Issue by PanderMusubi** [studioimaginaire/phue#40]
Please offer a package for Ubuntu/Debian so it can be distributed by these operating systems. See also https://bugs.launchpad.net/ubuntu/+bug/1414493

**Comment by natcl** [comment]
Hello, I'm not familiar with debian packaging, can't debian/ubuntu users just use pip to install python packages ?

**Comment by rec** [comment]
:+1: 

This is a pure Python program, so `pip` is a perfectly good distribution mechanism, and one which means that pyhue can be distributed to *nix, Windows, OS/X or whatever from the same, one package.

**Comment by PanderMusubi** [comment]
Even though pip is easy to use, in some settings it is not allowed and only packages from the default distro are allowed to be installed via apt-get. I know it sounds silly but some companies enforce these ways of working. Nevertheless, I am sure Ubuntu/Debian will pick up the package request, especially if development is continuous.
