### ISSUE TITLE
Please upload 0.9 on PyPI

### ISSUE THREAD

**Issue by deeplook** [studioimaginaire/phue#41]
Would you mind uploading the latest code (0.9 or so) on PyPI? Then any pip install commands used in whatever installation docs could reference a stable release rather than a work in progress.

Otherwise thanks for a cool package! Since it's essentially one module only, I can use it from Pythonista (http://omz-software.com/pythonista/) which has ``requests`` and other batteries built-in!

**Comment by natcl** [comment]
Hello, 0.9 is not released yet it's the dev version.  0.8 is the stable release.  Furthermore there was only a license change since 0.8 so not code change per se.  So for the moment there is no point uploading a new version.

**Comment by andres-torres-marroquin** [comment]
Can we have this version on pypi now? It fixes a bug when a light is removed. Thank you. Keep up the good work.
