### ISSUE TITLE
b.get_api() not displaying anything?

### ISSUE THREAD

**Issue by ChrisShire** [studioimaginaire/phue#42]
I'm sorry if this is just me being thick, but I'm totally new to Python (and programming/scripting in general). 

I have the library working and am able to turn my lights on/off etc, but the b.get_api() and b.get_light(1, 'on') commands don't print anything...

Is this supposed to be printed in the terminal or should I have written something more to get them to show? I'm not sure. I'm using Debian and OSX.

Thanks so much for the awesome software, it's really inspired me to learn some python and do some scripting!

**Comment by natcl** [comment]
Did you put print in front of the commands ?

```python
print b.get_api()
```

Also not the for the get methods, you cannot specify an action (like on or off) that's only to set so  you would write print b.get_light(1) not b.get_light(1,'on')

**Comment by ChrisShire** [comment]
Thank you so much! That worked. 

Really appreciate the help!
