### ISSUE TITLE
bri/hue/sat settings seem partially implemented.

### ISSUE THREAD

**Issue by jbum** [studioimaginaire/phue#43]
In my tests with a single Philips Hue bulb, I'm finding it possible to set brightness and hue, but not saturation.  Moreover, the spelling of bri/brightness varies, and hue cannot be set via the set_light method.

    # for bridge  
    b.set_light(1,'bri',250)          # works
    b.set_light(1,'brightness',250)   # no handler found
    b.set_light(1,'hue',40000)        # no handler found
    b.set_light(1,'sat',250)          # no handler found
    b.set_light(1,'saturation',250)   # no handler found

    # for individual light
    l.bri = 250               # no effect
    l.brightness = 250        # works
    l.hue = 40000             # works
    l.sat = 250               # no effect  (in my tests colormode is "hs")
    l.saturation = 250        # no handler found

**Comment by natcl** [comment]
There is something wrong with your setup.  Saturation works fine.
When using the set_light method the actual API names needs to be used (bri, hue, sat)
When using objects the full name is used.

Are you sure it's a standard hue bulb (not a lux ?)

You could try enabling debugging to see if the message reaches the Bridge and what is the answer:

```python
logging.basicConfig(level=logging.DEBUG)
```

**Comment by jbum** [comment]
Hmmm... Definitely hue, not lux.   For what it's worth, I installed via pip.

I'll see if logging turns up anything...

Jim

**Comment by jbum** [comment]
Found it.  I was passing strings instead of ints for hue and sat.  Thanks!
