### ISSUE TITLE
Removing light {1} breaks b.lights 

### ISSUE THREAD

**Issue by renini** [studioimaginaire/phue#46]
I had a broken light, which was light number 1, after replacing this light with a new light, my python script based on phue no longer works, the new light has number 5.

`lights = b.lights
`# Print light names
`for l in lights:
`    print(l.name)

results in
File "/usr/local/lib/python2.7/dist-packages/phue.py", line 588, in get_light_objects
    return [self.lights_by_id[x] for x in range(1, len(self.lights_by_id) + 1)]
KeyError: 1

when changing line 588, to
return [self.lights_by_id[x] for x in range(2, len(self.lights_by_id) + 1)]

the script works again but obviously doesn't list the last light (5) in my case because it starts with 2.
so you cannot assume lights always start at 1, apparently the bridge doesn't renumber them in order.

i will try to patch this with a pull req, but python is not my strongest language.

**Comment by natcl** [comment]
Thanks, let me know if you have questions !

**Comment by BillX86** [comment]
Simplest fix is replace:
 return [self.lights_by_id[x] for x in range(1, len(self.lights_by_id) + 1)]
by:
return [self.lights_by_id.values()]

**Comment by renini** [comment]
@BillX86 thanks that seems to work! @natcl any change you can commit that?

**Comment by natcl** [comment]
Yup will do soon !


--
lecaude.com 
studioimaginaire.com

**Comment by natcl** [comment]
Thanks, fixed with c48845992b476f4b1de9549ea5b5277399f56581

**Comment by renini** [comment]
thanks!
