### ISSUE TITLE
I'm having difficulties when the ip address of the Hue hub changes

### ISSUE THREAD

**Issue by TomMcBride** [studioimaginaire/phue#48]
I'm using both Windows 7 and a Raspberry Pi to control lights. I do testing and coding in Python mostly on Windows but the RPi does most of the controlling since I leave it on all the time. Everything works fine until I have a power outage (or, equivalently, disconnect and reconnect power to my router). I have a number of devices on my home network: 3 computers, a couple of printers, TiVo, etc. The Hue hub always seems to get a different ip address when this happens. This means that my programs no longer can connect to the hub. I can figure out what the new ip address is when this happens and change the programs but that's not enough. I find that I have to go through the press-the-button-on-the-hub process again for each system. Is there some way to avoid that?

I notice that I don't have to do anything like that on my iPad -- it doesn't seem to be bothered by the ip change. This problem doesn't happen often and the RPi sends me email to let me know about the problem. My difficulty is that I'm not always at home and there is no way to push the button remotely. Any ideas or suggestions would be welcome.

**Comment by bwbaugh** [comment]
Does `ping philips-hue` work on the terminal? If so, I believe you could have your program connect to that host name instead of the direct IP.

**Comment by natcl** [comment]
What router are you using ?

The best strategy is to tell your router to reserve an address for your bridge, this way it always stays the same. This is usually called 'DHCP reservation'.


--
lecaude.com 
studioimaginaire.com

**Comment by TomMcBride** [comment]
Thanks very much. I did find the DHCP reservation
      option on one of my router configuration screens. I think this
      will solve the problem. For what it's worth, the router in
      question is a Cisco Valet Plus M20. 
    
    On 5/26/2015 12:27 PM, Nathanaël
      Lécaudé wrote:
    
    What router are you using ?
      
      The best strategy is to tell your router to reserve an address for
      your bridge, this way it always stays the same. This is usually
      called 'DHCP reservation'.
      
      
      --
      lecaude.com 
      studioimaginaire.com 
      
      > Le 2015-05-26 à 12:09, Tom McBride
      <notifications@github.com> a écrit :
      > 
      > I'm using both Windows 7 and a Raspberry Pi to control
      lights. I do testing and coding in Python mostly on Windows but
      the RPi does most of the controlling since I leave it on all the
      time. Everything works fine until I have a power outage (or,
      equivalently, disconnect and reconnect power to my router). I have
      a number of devices on my home network: 3 computers, a couple of
      printers, TiVo, etc. The Hue hub always seems to get a different
      ip address when this happens. This means that my programs no
      longer can connect to the hub. I can figure out what the new ip
      address is when this happens and change the programs but that's
      not enough. I find that I have to go through the
      press-the-button-on-the-hub process again for each system. Is
      there some way to avoid that?
      > 
      > I notice that I don't have to do anything like that on my
      iPad -- it doesn't seem to be bothered by the ip change. This
      problem doesn't happen often and the RPi sends me email to let me
      know about the problem. My difficulty is that I'm not always at
      home and there is no way to push the button remotely. Any ideas or
      suggestions would be welcome.
      > 
      > —
      > Reply to this email directly or view it on GitHub.
      > 
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by carlosperate** [comment]
The DHCP reservation should definitely help you with this problem.
However I am more interested about the fact that you have to register your application again every time this happens. Does anybody know why this might happen? I don't see why when the bridge ends up with a different IP it would stop allowing requests from devices (or usernames) in the whitelist.

TomMcBride, does this happen as well when you reboot your raspberry pi?

**Comment by natcl** [comment]
This happens because the bridge information is stored as ip:key so if the ip changes, phue doesn't find the good credentials. You can check in your home folder for the settings file (.python_hue) and change your ip manually. It should then connect fine.

**Comment by carlosperate** [comment]
I see, thanks for the clarification natcl.

**Comment by TomMcBride** [comment]
It does not happen when I reboot the RPi. It seems
      that as long as the ip address stays the same, it just keeps
      working.
    
    On 5/26/2015 5:46 PM, Carlos wrote:
    
    
      The DHCP reservation should definitely help you with this
        problem.
        However I am more interested about the fact that you have to
        register your application again every time this happens. Does
        anybody know why this might happen? I don't see why when the
        bridge ends up with a different IP it would stop allowing
        requests from devices (or usernames) in the whitelist.
      TomMcBride, does this happen as well when you reboot your
        raspberry pi?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by TomMcBride** [comment]
Thanks. I just looked at the file you named,
      .python_hue, it is as you said. I suppose I could have just
      changed it to the new ip address. You are about to be able to tell
      that I'm very new to Linux. Why did I not see that file when I ran
      the ls command? I typed ls .python_hue and it showed the file. I
      could open it in the editor. Is there some magic associated with
      the initial period character? When I issue pwd, it shows
      /home/lights  .  Thanks, by the way, for taking the time to
      answer.
    
    On 5/26/2015 5:50 PM, Nathanaël Lécaudé
      wrote:
    
    
      This happens because the bridge information is stored as ip:key
        so if the ip changes, phue doesn't find the good credentials.
        You can check in your home folder for the settings file
        (.python_hue) and change your ip manually. It should then
        connect fine.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by trainman419** [comment]
Files that start with a dot are considered "hidden" on Linux. You can see them with `ls -a` (for all)
