### ISSUE TITLE
No handlers could be found for logger "phue"

### ISSUE THREAD

**Issue by YannisDC** [studioimaginaire/phue#53]
I just installed my bridge and it's working properly using the app. It also worked a few times using the hue basic example but now I'm getting this warning: No handlers could be found for logger "phue"
The lamps do get set on but not on the right brightness, it's quite low.

**Comment by DeastinY** [comment]
Did you remember ?

> import logging
 logging.basicConfig()

Also make sure you set the brightness to a value between 1 and 254, not 1 and 100.

**Comment by aycgit** [comment]
that logging thing fixes it so i think you can clean your issues by closing this one :)

**Comment by natcl** [comment]
Thanks !
