### ISSUE TITLE
Broken with commit a8863fb9a3cdbc93a0aaf6645912a050609fba98

### ISSUE THREAD

**Issue by fssi** [studioimaginaire/phue#59]
on line 531, the installation of phue.py on a blank system and first connection to the bridge won't work because the .python_hue file can't be opened for read (the file doesn't exist.)

I guess a workaround is to create a .python_hue file with valid JSON data so that it can be opened and loaded, but perhaps a better check would be to load the file only if it exists?

Great work otherwise!

**Comment by natcl** [comment]
I'm not sure I understand what you mean by blank system ?
The .python_hue file is created automatically the first time you connect after having pressing the link button on the Bridge.

**Comment by natcl** [comment]
Oh I see.
This comes from an earlier pull request that changed the file mode form w to r+
I just reverted to "w"
Can you let me know if it fixes the problem ?
Thanks !

**Comment by natcl** [comment]
Hmm hold on the last pull request seems to mess more things than I thought..

**Comment by natcl** [comment]
Thanks just reverted !
