### ISSUE TITLE
Observe light bulb changes

### ISSUE THREAD

**Issue by vanniktech** [studioimaginaire/phue#88]
I'd like to observe light bulb changes.

Instead of querying every X seconds and asking for the state of the light bulbs it would be cool if I could somehow register myself to light changes and observe changes.

So far I haven't found this in the README nor do I know whether the bridge itself supports something like this.

**Comment by vanniktech** [comment]
Alright that's what I thought. However the hue android app is capable of that so maybe all they're doing internally is also just a simple poll.

**Comment by demosdemon** [comment]
The bridge can handle the polling. I can't find it anymore, but the official docs said the bridge can handle something like 5ops/s.

**Comment by vanniktech** [comment]
How are the Android Apps doing it though? When I turn off the light the app immediately notices the light change. I can't imagine that the Android App is pulling every second for each lamp the state.

**Comment by caedn** [comment]
Maybe they are polling group 0, which gets you the state for all lights. That can be feasibly done once per second.

**Comment by vanniktech** [comment]
Got the change to talk to one of the engineers. They do just poll it every second. Hence I'll close this issue.
