### ISSUE TITLE
Can not import Bridge

### ISSUE THREAD

**Issue by neodd70** [studioimaginaire/phue#91]
I am trying to set this up and please forgive me as I am new to this but after I installed phue I tried to do a test and I keep getting this error

Traceback (most recent call last):
  File "phue.py", line 2, in <module>
    from phue import Bridge
  File "/home/mike/hue/phue.py", line 2, in <module>
    from phue import Bridge
ImportError: cannot import name Bridge

can anyone shed some light as to what might be causing this error?

**Comment by natcl** [comment]
Sounds like the library is not installed properly, how did you install it ?

**Comment by demosdemon** [comment]
Your script can't be called `phue.py` and also import a module called `phue`. Python treats that as a recursive import. Rename your script file to anything else.
