### ISSUE TITLE
allow the user to select the username

### ISSUE THREAD

**Issue by Sispheor** [studioimaginaire/phue#97]
During the first connection, the username is registered into the bridge. 
It's seems that this username is like a token. You need to specify into your REST requests. So, it could be a good point to enhance the security and let the user select this username instead of give a default one.

The first connection would be sometnig like this:
```python
b.connect(username="my_private_and_secret_username")
```

**Comment by demosdemon** [comment]
The bridge generates a random username.

**Comment by Sispheor** [comment]
And then you store it into the .python_hue file, right? 
Ok, should be good enough so.

Ok, I let you decide to close the PR or keep the idea for later.

Thanks for the lib anyway!

**Comment by demosdemon** [comment]
The old api used to allow you to create your own username, but Philips changed that. You can no longer input a custom username. You have to use the username the bridge gives you.

**Comment by Sispheor** [comment]
OK, thank you for your time and your answer. I close the issue then.
