### ISSUE TITLE
very very new, need help saying "host is required"

### ISSUE THREAD

**Issue by ajramnot** [studioimaginaire/phue#99]
Hello, i am receiving the following message when trying to access phue.py:

pi@raspberrypi:/usr/local/lib/python2.7/dist-packages $ sudo python phue.py
usage: phue.py [-h] --host HOST [--config-file-path CONFIG_FILE_PATH]
phue.py: error: argument --host is required

Please excuse my ignorance. 

Thank you

**Comment by MiguelRipoll23** [comment]
Host probably means the IP address of the bridge, you can find it [here](https://www.meethue.com/api/nupnp). If internalipaddress doesn't appear there, then you need to use the Philips Hue app, move to Explore and log in.
